version: "3"

services:
  traefik:
    image: "traefik:1.6.5"
    command:
      - "--debug"
      - "--api"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.watch"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - traefik_backends

networks:
  traefik_backends:
    external: true
