version: "3"

services:
  elasticsearch:
    image: elasticsearch
    deploy:
      labels:
        - "traefik.backend=elasticsearch-cluster"
        - "traefik.backend.healthcheck.path=/"
        - "traefik.frontend.rule=PathPrefixStrip: /elasticsearch-cluster"
        - "traefik.port=9200"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - traefik_backends

networks:
  traefik_backends:
    external: true
